name: hajeri_demo
description: A flutter project for client at AM Ventures, Aurangabad.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.0.0
  convex_bottom_bar: ^2.7.1+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  excel: ^1.1.5
  file_picker: ^3.0.0
  flutter_downloader: ^1.5.2
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.3
  geolocator: ^7.0.1
  google_fonts: ^1.1.1
  google_maps_flutter: ^2.0.1
  horizontal_data_table: ^2.5.0
  http: ^0.12.0+1
  image_gallery_saver: ^1.6.8
  json_serializable: ^3.3.0
  modal_progress_hud: ^0.1.3
  month_picker_dialog: ^0.3.3
  open_file: ^3.1.0
  permission_handler: ^6.1.1
  qr_code_scanner: ^0.3.5
  qr_flutter: ^4.0.0
  screenshot: ^0.3.0
  flutter_local_notifications: ^5.0.0
  shared_preferences: ^2.0.4
  shimmer: ^1.1.2
  sms_autofill: ^1.3.1
  syncfusion_flutter_xlsio: ^18.3.35-beta.1
  # syncfusion_flutter_calendar: ^18.4.48
  syncfusion_flutter_datagrid: ^18.4.48-beta
  syncfusion_flutter_pdf: ^18.4.48-beta
  toast: ^0.1.5
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
