name: hajeri_ios CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # This job will run on macos virtual machine
    runs-on: macos-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.0"
          channel: "stable"
      # Get flutter dependencies.
      - name: Install pub Dependencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      # - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      #- run: flutter analyze .

      # # Run widget tests for our flutter project.
      # - run: flutter test

      # Build ios app.
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: runner
          path: build/ios/iphoneos/app.ipa
